### ISSUE TITLE
Augmenting Validator in TypeScript stopped working

### ISSUE THREAD

**Issue by elektromodulator** [ctavan/express-validator#487]
Augmenting the Validator interface in typescript no longer works.
I am trying to add custom validators to Validator interface using:
``` TypeScript
import expressValidator = require("express-validator");

declare module "express-validator" {
    export interface Validator {
        isEmailAvailable(): ExpressValidator.Validator;
        isPasswordValid(): ExpressValidator.Validator;
    }
}
```
It worked in version 3.1.3, not working in version 3.2.0.

I got the following error message:
`src/types/express-validator.d.ts(3,16): error TS2671: Cannot augment module 'express-validator' because it resolves to a non-module entity.`
 
Using `declare namespace ExpressValidator` instead of `module` also does not work, tsc simply sees it as a different namespace and interface, and won't merge them.

**Comment by gustavohenke** [comment]
Can you check whether the discussion in #352 helps you?
There were some related discussion on other issues/PRs as well.

Also, `src/types/express-validator.d.ts` doesn't seem like something from this project.

**Comment by elektromodulator** [comment]
Using version 3.2.1 if express-validator solves this issue.

**Comment by gustavohenke** [comment]
> src/types/express-validator.d.ts is the file where the augmentation code is

Ah, sure! D'oh!

I'm glad you found your way around 😃
