### ISSUE TITLE
Asynchronous Validation in 2.20.2 don't work

### ISSUE THREAD

**Issue by poupou-keud** [ctavan/express-validator#220]
Hi, 

It seems that there's something wrong with the use of bluebird in 2.20.2.

```
app.use(expressValidator({
  customValidators: {
    isUsernameAvailable: function(username) {
      return new Promise(function(resolve, reject) {
        resolve(true)
      });
    }
  }
}));
```
And got the message **TypeError: promise.reflect is not a function** in console

I downgraded to 2.20.1 and it works.

**Comment by rustybailey** [comment]
Weird. When you do npm install, does it install bluebird 3.3.x as one of our dependencies? All of our tests pass relating to async errors, so that's the only thing I can think of...

**Comment by poupou-keud** [comment]
Yes 3.3.4. Maybe i'm doing something wrong.

I reproduce it with a simple case. Express init, add in package json **"express-validator": "2.20.2"**

app.js

```
var bodyParser = require('body-parser');
var express = require('express');
var expressValidator = require('express-validator');
var path = require('path');

var app = express();

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: true}));
app.use(
    expressValidator(
        {
            customValidators: {
                testAsync: function (param) {
                    return new Promise(
                        function (resolve, reject) {
                            resolve();
                        }
                    );
                }
            }
        }
    )
);

app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'jade');

app.get(
    '/test',
    function (req, res) {
        res.render('index');
    }
);

app.post(
    '/test',
    function (req, res) {
        req.checkBody('param', 'param ko').testAsync();

        req.asyncValidationErrors()
            .then(
                function () {
                    res.send('ok');
                }
            )
            .catch(
                function (errors) {
                    console.log('catch');
                    console.log(errors);
                    res.send(errors);
                }
            )
        ;
    }
);

module.exports = app;
```

And in console, after submit the form :

```
catch
[TypeError: promise.reflect is not a function]
```

**Comment by rustybailey** [comment]
@AuspeXeu can you look into this since you made those changes? If not, I won't be able to look into this until Monday.

**Comment by AuspeXeu** [comment]
Sorry, I am super busy myself.

**Comment by rustybailey** [comment]
@poupou-keud Are you using the native Node promises or Bluebird promises? If the former, I think that is where the issue may be. Our dummy app in our tests assume that users are passing us a Bluebird promise (https://github.com/ctavan/express-validator/blob/master/test/helpers/app.js#L5). We probably need to be converting promises to Bluebird promises in `express-validator.js` so that promise.reflect() is a valid function.

**Comment by poupou-keud** [comment]
Works fine in 2.20.3

Thx
